const states = {
  '000': {
      code: '000',
      article: 'Elemental',
      articulo: 'Elemental',
      concept: 'Serenity',
      concepto: 'Serenidad',
      archetype: 'Monk',
      arquetipo: 'Monge',
      colour: 'Black',
      color: 'Negro',
      mbti: 'I--P',
      location: 'Wilderness',
      localidad: 'Naturaleza',
      map: 'Open Range, Retreat, Getaway',
      mapa: 'Camp Abierto, Retiro, Excursion'
  },
  '001': {
      code: '001',
      article: 'Inspirational',
      articulo: 'Inspiracional',
      concept: 'Charm',
      concepto: 'Encanto',
      archetype: 'Actor',
      arquetipo: 'Actor',
      colour: 'Navi',
      color: 'Marino',
      mbti: '-NFP',
      location: 'Garden',
      localidad: 'Jardín',
      map: 'Botanical Garden, Zoo, Fair',
      mapa: 'Jardín Botánico, Zoológico, Feria'
  },
  '002': {
      code: '002',
      article: 'Sentimental',
      articulo: 'Sentimental',
      concept: 'Feeling',
      concepto: 'Sentimiento',
      archetype: 'Poet',
      arquetipo: 'Poeta',
      colour: 'Blue',
      color: 'Índigo',
      mbti: 'INFP',
      location: 'Auditorium',
      localidad: 'Auditorio',
      map: 'Concert Hall, Theatre, Opera House',
      mapa: 'Recital, Teatro, Ópera'
  },
  '010': {
      code: '010',
      article: 'Conceptual',
      articulo: 'Conceptual',
      concept: 'Knowledge',
      concepto: 'Conocimiento',
      archetype: 'Researcher',
      arquetipo: 'Investigador',
      colour: 'Forest',
      color: 'Verde Oscuro',
      mbti: '-NTP',
      location: 'Field',
      localidad: 'Campo',
      map: 'Research Center, Journals, Excursion',
      mapa: 'Centro de Investigación, Excursión'
  },
  '011': {
      code: '011',
      article: 'Ideational',
      articulo: 'Ideacional',
      concept: 'Imagination',
      concepto: 'Imaginación',
      archetype: 'Storyteller',
      arquetipo: 'Cuentacuentos',
      colour: 'Teal',
      color: 'Verde Azulado',
      mbti: 'EN-P',
      location: 'Cafe',
      localidad: 'Café',
      map: 'Dialogue, Reading, Publications',
      mapa: 'Diálogo, Lectura, Publicaciones'
  },
  '012': {
      code: '012',
      article: 'Existential',
      articulo: 'Existencial',
      concept: 'Meaning',
      concepto: 'Significado',
      archetype: 'Therapist',
      arquetipo: 'Terapeuta',
      colour: 'Aqua',
      color: 'Aqua',
      mbti: '-NF-',
      location: 'Sanctuary',
      localidad: 'Santuario',
      map: 'Temple, Memorial, Museum',
      mapa: 'Templo, Memorial, Museo'
  },
  '020': {
      code: '020',
      article: 'Analytical',
      articulo: 'Analítico',
      concept: 'Reason',
      concepto: 'Raciocinio',
      archetype: 'Analyst',
      arquetipo: 'Analista',
      colour: 'Green',
      color: 'Verde',
      mbti: 'INTP',
      location: 'Study',
      localidad: 'Estudio',
      map: 'Desk, Board, Observatory',
      mapa: 'Escritorio, Pizzarra, Observatorio'
  },
  '021': {
      code: '021',
      article: 'Instructional',
      articulo: 'Instruccional',
      concept: 'Ingenuity',
      concepto: 'Ingenio',
      archetype: 'Instructor',
      arquetipo: 'Instructor',
      colour: 'Emerald',
      color: 'Esmeralda',
      mbti: '-NT-',
      location: 'Seminar',
      localidad: 'Seminario',
      map: 'Forum, Expo, Classroom',
      mapa: 'Forum, Expo, Aula'
  },
  '022': {
      code: '022',
      article: 'Philosophical',
      articulo: 'Filosófico',
      concept: 'Morality',
      concepto: 'Moralidad',
      archetype: 'Philosopher',
      arquetipo: 'Filosófo',
      colour: 'Cyan',
      color: 'Ciano',
      mbti: 'IN-J',
      location: 'Library',
      localidad: 'Biblioteca',
      map: 'Archives, Mentoring, History',
      mapa: 'Archivos, Mentoría, Historia'
  },
  '100': {
      code: '100',
      article: 'Sensorial',
      articulo: 'Sensorial',
      concept: 'Alertness',
      concepto: 'Alerta',
      archetype: 'Sentinel',
      arquetipo: 'Sentinela',
      colour: 'Maroon',
      color: 'Vino',
      mbti: '-S-P',
      location: 'Park',
      localidad: 'Parque',
      map: 'Outdoor Sports, Hunting, Yard',
      mapa: 'Deportes De Campo, Cacería, Parque'
  },
  '101': {
      code: '101',
      article: 'Jovial',
      articulo: 'Jovial',
      concept: 'Mood',
      concepto: 'Humor',
      archetype: 'Entertainer',
      arquetipo: 'Animador',
      colour: 'Purple',
      color: 'Morado',
      mbti: 'ESFP',
      location: 'Club',
      localidad: 'Club',
      map: 'Cafeteria, Bar, Party Area',
      mapa: 'Cafetería, Bar, Salón De Fiestas'
  },
  '102': {
      code: '102',
      article: 'Sensual',
      articulo: 'Sensual',
      concept: 'Taste',
      concepto: 'Gusto',
      archetype: 'Designer',
      arquetipo: 'Diseñador',
      colour: 'Violet',
      color: 'Violeta',
      mbti: '--F-',
      location: 'Gallery',
      localidad: 'Galería',
      map: 'Art Exhibit, Restaurant, Runway',
      mapa: 'Exhibición De Arte, Restaurant, Pasarela'
  },
  '110': {
      code: '110',
      article: 'Factual',
      articulo: 'Factual',
      concept: 'Objectivity',
      concepto: 'Objetividad',
      archetype: 'Merchant',
      arquetipo: 'Mercader',
      colour: 'Olive',
      color: 'Olivo',
      mbti: 'ESTP',
      location: 'Market',
      localidad: 'Mercado',
      map: 'Commerce, Trading, Casino',
      mapa: 'Comercio, Banca, Casino'
  },
  '111': {
      code: '111',
      article: 'Social',
      articulo: 'Social',
      concept: 'Comunication',
      concepto: 'Comunicación',
      archetype: 'Socializer',
      arquetipo: 'Socializador',
      colour: 'Gray',
      color: 'Gris',
      mbti: 'E---',
      location: 'Plaza',
      localidad: 'Plaza',
      map: 'Hallway, Media, Main Hub',
      mapa: 'Pasillo, Medios De Comunciación, Centro'
  },
  '112': {
      code: '112',
      article: 'Congenial',
      articulo: 'Congenial',
      concept: 'Community',
      concepto: 'Comunidad',
      archetype: 'Diplomat',
      arquetipo: 'Diplomático',
      colour: 'Lavander',
      color: 'Lavanda',
      mbti: 'ENFJ',
      location: 'Community Center',
      localidad: 'Centro Comunitario',
      map: 'Cultural Center, Embassy, Hospitality',
      mapa: 'Centro Cultural, Embajada, Hotelería'
  },
  '120': {
      code: '120',
      article: 'Technical',
      articulo: 'Técnico',
      concept: 'Functionality',
      concepto: 'Funcionalidad',
      archetype: 'Technitian',
      arquetipo: 'Técnico',
      colour: 'Lime',
      color: 'Limón',
      mbti: '--T-',
      location: 'Lab',
      localidad: 'Laboratorio',
      map: 'Systems, Technology, Accounting',
      mapa: 'Sistemas, Tecnología, Contabilidad'
  },
  '121': {
      code: '121',
      article: 'Directorial',
      articulo: 'Directorial',
      concept: 'Direction',
      concepto: 'Dirección',
      archetype: 'Director',
      arquetipo: 'Director',
      colour: 'Mint',
      color: 'Menta',
      mbti: 'ENTJ',
      location: 'Civic Center',
      localidad: 'Centro Civil',
      map: 'Organization, Club, Politic Arena',
      mapa: 'Organización, Club, Arena Política'
  },
  '122': {
      code: '122',
      article: 'Judicial',
      articulo: 'Judicial',
      concept: 'Judgement',
      concepto: 'Juicio',
      archetype: 'Judge',
      arquetipo: 'Juez',
      colour: 'Sky',
      color: 'Celeste',
      mbti: '-N-J',
      location: 'Court',
      localidad: 'Corte',
      map: 'Assembly, Advisory, Congress',
      mapa: 'Asamblea, Consejería, Congreso'
  },
  '200': {
      code: '200',
      article: 'Martial',
      articulo: 'Marcial',
      concept: 'Might',
      concepto: 'Arrojo',
      archetype: 'Warrior',
      arquetipo: 'Guerrero',
      colour: 'Red',
      color: 'Rojo',
      mbti: 'IS-P',
      location: 'Arena',
      localidad: 'Arena',
      map: 'Stadium, Dojo, Track & Field',
      mapa: 'Estadio, Dojo, Campo Y Pista'
  },
  '201': {
      code: '201',
      article: 'Sensational',
      articulo: 'Sensacional',
      concept: 'Attitude',
      concepto: 'Actitud',
      archetype: 'Performer',
      arquetipo: 'Actor',
      colour: 'Pink',
      color: 'Fuscia',
      mbti: '-SF-',
      location: 'Gym',
      localidad: 'Gimnasio',
      map: 'Ring, Stage, Dance Floor',
      mapa: 'Pista, Escenario, Salón De Baile'
  },
  '202': {
      code: '202',
      article: 'Artisanal',
      articulo: 'Artesanal',
      concept: 'Passion',
      concepto: 'Pasión',
      archetype: 'Artisan',
      arquetipo: 'Artesano',
      colour: 'Magenta',
      color: 'Magenta',
      mbti: 'ISFJ',
      location: 'Studio',
      localidad: 'Atelier',
      map: 'Atelier, Crafts, Kitchen',
      mapa: 'Artesanía, Cocina, Manualidades'
  },
  '210': {
      code: '210',
      article: 'Practical',
      articulo: 'Práctico',
      concept: 'Aptitude',
      concepto: 'Aptitud',
      archetype: 'Mechanic',
      arquetipo: 'Mecánico',
      colour: 'Orange',
      color: 'Naranja',
      mbti: '-ST-',
      location: 'Workshop',
      localidad: 'Taller',
      map: 'Warehouse, Garage, Construction',
      mapa: 'Almacen, Garage, Construcción'
  },
  '211': {
      code: '211',
      article: 'Official',
      articulo: 'Oficial',
      concept: 'Service',
      concepto: 'Servicio',
      archetype: 'Officer',
      arquetipo: 'Oficial',
      colour: 'Coral',
      color: 'Coral',
      mbti: 'ES-J',
      location: 'Service Center',
      localidad: 'Centro De Servicio',
      map: 'Security, Life Guarding, Agency',
      mapa: 'Seguridad, Agencia, Superintendencia'
  },
  '212': {
      code: '212',
      article: 'Protectoral',
      articulo: 'Protectoral',
      concept: 'Security',
      concepto: 'Seguridad',
      archetype: 'Caretaker',
      arquetipo: 'Guardián',
      colour: 'Rose',
      color: 'Rosa',
      mbti: '-SFJ',
      location: 'Clinic',
      localidad: 'Clínica',
      map: 'Aid, Health, Care Center',
      mapa: 'Asistencia, Centro De Salud, Guardería'
  },
  '220': {
      code: '220',
      article: 'Industrial',
      articulo: 'Industrial',
      concept: 'Productivity',
      concepto: 'Productividad',
      archetype: 'Producer',
      arquetipo: 'Productor',
      colour: 'Yellow',
      color: 'Amarillo',
      mbti: 'ISTJ',
      location: 'Industry',
      localidad: 'Industria',
      map: 'Factory, Engineering, Manufactoring',
      mapa: 'Fábrica, Ingeniería, Manufactura'
  },
  '221': {
      code: '221',
      article: 'Managerial',
      articulo: 'Empresarial',
      concept: 'Motivation',
      concepto: 'Motivación',
      archetype: 'Manager',
      arquetipo: 'Manager',
      colour: 'Gold',
      color: 'Dorado',
      mbti: '-STJ',
      location: 'Company',
      localidad: 'Compañía',
      map: 'Venture, Business, Enterprise',
      mapa: 'Projectos, Negocios, Empresas'
  },
  '222': {
      code: '222',
      article: 'Imperial',
      articulo: 'Imperial',
      concept: 'Resposability',
      concepto: 'Responsabilidad',
      archetype: 'Emperor',
      arquetipo: 'Emperador',
      colour: 'White',
      color: 'Blanco',
      mbti: 'I--J',
      location: 'Management',
      localidad: 'Gerencia',
      map: 'Palace, Tribune, Government',
      mapa: 'Palacio, Tribunal, Gobierno'
  }
}

export default states;