class ContentTree {
  constructor() {
    this.nodes = [];
  }


    /*
     * Remove basic inline Markdown characters when producing plain text.
     *
     * This does not attempt to implement the complete Markdown standard.
     * It is sufficient for the test content and can later be replaced
     * with a full Markdown parser.
     */
  static cleanInlineMarkdown(text) {
    return text
      .replace(/`([^`]+)`/g, "$1")
      .replace(/\*\*([^*]+)\*\*/g, "$1")
      .replace(/\*([^*]+)\*/g, "$1")
      .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
      .trim();
  }


    /*
     * Convert Markdown into a flat sequence of content elements.
     */

    static parseMarkdown(markdown) {
      const lines = markdown
        .replace(/\r/g, "")
        .split("\n");

      const elements = [];
      let paragraph = [];

      function finishParagraph() {
        if (!paragraph.length) return;

        elements.push({
          tag: "p",
          text: ContentTree.cleanInlineMarkdown(paragraph.join(" "))
        });

        paragraph = [];
      }

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();

        const headingMatch =
          line.match(/^(#{1,6})\s+(.+)$/);

        const unorderedListMatch =
          line.match(/^[-*+]\s+(.+)$/);

        const orderedListMatch =
          line.match(/^\d+[.)]\s+(.+)$/);

        if (!line) {
          finishParagraph();
          continue;
        }

        if (headingMatch) {
          finishParagraph();

          elements.push({
            tag: "h" + headingMatch[1].length,
            text: ContentTree.cleanInlineMarkdown(headingMatch[2])
          });

          continue;
        }

        if (unorderedListMatch || orderedListMatch) {
          finishParagraph();

          const listType =
            unorderedListMatch ? "ul" : "ol";

          const items = [];
          let currentMatch =
            unorderedListMatch || orderedListMatch;

          while (currentMatch) {
            items.push(
              ContentTree.cleanInlineMarkdown(currentMatch[1])
            );

            i++;

            const nextLine =
              lines[i]?.trim() || "";

            currentMatch =
              listType === "ul"
                ? nextLine.match(/^[-*+]\s+(.+)$/)
                : nextLine.match(/^\d+[.)]\s+(.+)$/);
          }

          i--;

          elements.push({
            tag: listType,
            items
          });

          continue;
        }

        if (line.startsWith("> ")) {
          finishParagraph();

          elements.push({
            tag: "blockquote",
            text: ContentTree.cleanInlineMarkdown(line.slice(2))
          });

          continue;
        }

        paragraph.push(line);
      }

      finishParagraph();

      return elements;
    }


    /*
     * Convert semantic HTML into the same flat sequence.
     */

    static parseHTML(root) {
      const selector = [
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "p",
        "ul",
        "ol",
        "blockquote",
        "pre"
      ].join(",");

      return Array
        .from(root.querySelectorAll(selector))
        .filter(element => {
          /*
           * Paragraphs or lists generated by the interface should not
           * become part of the content if this function runs again.
           */

          return !element.closest("[data-content-interface]");
        })
        .map(element => {
          const tag =
            element.tagName.toLowerCase();

          if (tag === "ul" || tag === "ol") {
            return {
              tag,
              items: Array
                .from(element.children)
                .filter(child => child.tagName === "LI")
                .map(item => item.textContent.trim())
            };
          }

          return {
            tag,
            text: element.textContent.trim()
          };
        });
    }

    /*
     * Turn the flat sequence into a hierarchical content tree.
     *
     * Every heading contains everything following it until another
     * heading of the same or a higher rank appears.
     */

    static createContentTree(elements) {
      const root = {};

      /*
       * Heading numbers are global by heading level:
       *
       * h1_0
       * h2_0
       * h2_1
       * h3_0
       */

      const headingCounts = {
        h1: 0,
        h2: 0,
        h3: 0,
        h4: 0,
        h5: 0,
        h6: 0
      };

      /*
       * The stack records the currently open heading hierarchy.
       */

      const stack = [
        {
          level: 0,
          content: root
        }
      ];

      /*
       * Paragraph and list numbering restarts inside each section.
       */

      const localCounts = new WeakMap();

      function nextLocalKey(content, type) {
        let counts = localCounts.get(content);

        if (!counts) {
          counts = {};
          localCounts.set(content, counts);
        }

        const index = counts[type] || 0;
        counts[type] = index + 1;

        return type + "_" + index;
      }

      for (const element of elements) {
        const headingMatch =
          element.tag.match(/^h([1-6])$/);

        if (headingMatch) {
          const level =
            Number(headingMatch[1]);

          /*
           * Close headings of the same or lower hierarchy.
           */

          while (
            stack[stack.length - 1].level >= level
          ) {
            stack.pop();
          }

          const parentContent =
            stack[stack.length - 1].content;

          const headingKey =
            element.tag + "_" +
            headingCounts[element.tag]++;

          const headingNode = {
            type: element.tag,
            text: element.text,
            content: {}
          };

          parentContent[headingKey] =
            headingNode;

          stack.push({
            level,
            content: headingNode.content
          });

          continue;
        }

        const currentContent =
          stack[stack.length - 1].content;

        const blockKey =
          nextLocalKey(
            currentContent,
            element.tag
          );

        if (element.items) {
          currentContent[blockKey] = {
            type: element.tag,
            items: element.items
          };
        } else {
          currentContent[blockKey] = {
            type: element.tag,
            text: element.text
          };
        }
      }

      return root;
    }


    /*
     * Render the content tree as semantic HTML.
     */

    static renderTree(tree) {
      const fragment = document.createDocumentFragment();

      for (const [key, node] of Object.entries(tree)) {
        const headingMatch = key.match(/^h([1-6])_/);

        if (headingMatch) {
          const section = document.createElement("section");
          section.className = key;

          const displayLevel = Math.min(Number(headingMatch[1]), 6);

          const heading = document.createElement( "h" + displayLevel);

          heading.textContent = node.text;

          section.append(heading);

          if (node.content) {
            section.append(ContentTree.renderTree(node.content));
          }

          fragment.append(section);
          continue;
        }

        const block = document.createElement("div");

        block.className = "content-block";

        if (node.type === "ul" || node.type === "ol") {
          const list = document.createElement(node.type);
          for (const itemText of node.items) {
            const item = document.createElement("li");
            item.textContent = itemText;
            list.append(item);
          }
          block.append(list);
        } else if (
          node.type === "blockquote"
        ) {
          const quote = document.createElement("blockquote");
          quote.textContent = node.text;
          block.append(quote);
        } else if (
          node.type === "pre"
        ) {
          const pre = document.createElement("pre");
          pre.textContent = node.text;
          block.append(pre);
        } else {
          const paragraph = document.createElement("p");
          paragraph.textContent = node.text;
          block.append(paragraph);
        }
        fragment.append(block);
      }

      return fragment;
    }

    static get content() {

      if (window.contentTree) return window.contentTree;

      const markdownSource = document.querySelector("#markdown-source");
      const htmlSource = document.body;

      let sourceType;
      let parsedElements;

      if (markdownSource) {
        sourceType = "Markdown: #markdown-source";
        parsedElements = ContentTree.parseMarkdown( markdownSource.textContent );
      } else {
        sourceType = htmlSource === document.body ? "HTML: body" : "HTML: main";
        parsedElements = ContentTree.parseHTML(htmlSource);
      }

      const contentTree = ContentTree.createContentTree(parsedElements);

      return window.contentTree = contentTree;
    }
    
}